config/routes.rb
JqueryApp::Application.routes.draw do
  resources :currencies

  resources :addresses

  resources :districts  do
collection do
get "load_states"
post "load_states"
end
end
  resources :states 

  resources :countries

end

app/models/currency.rb
class Currency < ActiveRecord::Base
belongs_to :country
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @currencies }
    end
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.json
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render json: @currency, status: :created, location: @currency }
      else
        format.html { render action: "new" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.json
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to currencies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :country_id %><br />
    <%= f.collection_select :country_id, Country.order('name'), :id, :name ,{:prompt=>'Select Country'}%>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<table>
  <tr>
    <th>Country</th>	
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @currencies.each do |currency| %>
  <tr>
    <td><%= raw currency.country.name %></td>	
    <td><%= raw currency.name %></td>
    <td><%= link_to 'Show', currency %></td>
    <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
    <td><%= link_to 'Destroy', currency, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @currency.name %>
</p>


<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>