config/routes.rb
JqueryApp::Application.routes.draw do
  resources :currencies

  resources :addresses

  resources :districts  do
collection do
get "load_states"
post "load_states"
end
end
  resources :states 

  resources :countries

end

app/models/district.rb
class District < ActiveRecord::Base

belongs_to :country
belongs_to :state

private

def request_state_and_city_validation_based_on_zipcode
poll = true
if poll loc = MultiGeocoder.geocode("#{self.zip_code}, US") 
end

unless loc.success errors.add(:zip_code, "Unable to geocode your location from zipcode entered.") 
else
errors.add(:country, "Country doesn't matches with zipcode entered") if self.country.name != loc.country.name  
end 
end
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  # GET /districts
  # GET /districts.json
  def index
    @districts = District.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @districts }
    end
  end

  # GET /districts/1
  # GET /districts/1.json
  def show
    @district = District.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @district }
    end
  end

  # GET /districts/new
  # GET /districts/new.json
  def new
    @district = District.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @district }
    end
  end

  # GET /districts/1/edit
  def edit
    @district = District.find(params[:id])
  end

  # POST /districts
  # POST /districts.json
  def create
    @district = District.new(params[:district])

    respond_to do |format|
      if @district.save
        format.html { redirect_to @district, notice: 'District was successfully created.' }
        format.json { render json: @district, status: :created, location: @district }
      else
        format.html { render action: "new" }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /districts/1
  # PUT /districts/1.json
  def update
    @district = District.find(params[:id])

    respond_to do |format|
      if @district.update_attributes(params[:district])
        format.html { redirect_to @district, notice: 'District was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1
  # DELETE /districts/1.json
  def destroy
    @district = District.find(params[:id])
    @district.destroy

    respond_to do |format|
      format.html { redirect_to districts_url }
      format.json { head :ok }
    end
  end

	def load_states

		@currency=Currency.where(:country_id=>params[:id])

		@address=Address.where(:country_id=>params[:id])
		
	end
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/views/districts/_form.html.erb
<%= form_for(@district) do |f| %>
  <% if @district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@district.errors.count, "error") %> prohibited this district from being saved:</h2>

      <ul>
      <% @district.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br />
    <%= f.collection_select :country_id, Country.order('name'), :id, :name ,{:prompt=>'Select Country'}%>
  </div>
  <div class="field">
   <%= f.label :currency,:id =>"state" %><br />
    <%= f.text_field :name%>
  </div>
<div class="wrapper1" style="display:none !important;"> 
	<div class="field">
    <%= f.label :address ,:id =>"label_address"%><br />
    <%= f.text_field :address %>
  </div>
	<div class="field">
    <%= f.label :city ,:id =>"label_city"%><br />
    <%= f.text_field :city %>
  </div>
	<div class="field">
    <%= f.label :number ,:id =>"label_number"%><br />
    <%= f.text_field :number %>
  </div>
	<div class="field">
    <%= f.label :street_name,:id =>"label_street" %><br />
    <%= f.text_field :street_name %>
  </div>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
$("#district_country_id").change(function () {
 $.ajax({
            url: '/districts/load_states',
            type: "POST",
            data: { 'id' : $("#district_country_id").val() }

                    });
$(".wrapper1").show();

});

</script>

app/views/districts/_load_states.html.erb
<%#= label_tag @states[0].name %>
<%= collection_select(:district,:state_id, @states, :id, :name) %>

app/views/districts/edit.html.erb
<h1>Editing district</h1>

<%= render 'form' %>

<%= link_to 'Show', @district %> |
<%= link_to 'Back', districts_path %>

app/views/districts/index.html.erb
<h1>Listing districts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @districts.each do |district| %>
  <tr>
    <td><%= district.name %></td>
    <td><%= district.country_id %></td>
    <td><%= district.state_id %></td>
    <td><%= link_to 'Show', district %></td>
    <td><%= link_to 'Edit', edit_district_path(district) %></td>
    <td><%= link_to 'Destroy', district, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New District', new_district_path %>

app/views/districts/new.html.erb
<h1>New district</h1>

<%= render 'form' %>

<%= link_to 'Back', districts_path %>

app/views/districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @district.name %>
</p>

<p>
  <b>Country:</b>
  <%= @district.country_id %>
</p>

<p>
  <b>State:</b>
  <%= @district.state_id %>
</p>


<%= link_to 'Edit', edit_district_path(@district) %> |
<%= link_to 'Back', districts_path %>